name: Build & Test

on:
  push:
    branches-ignore:
      - master
      - release/prod
      - gh-pages
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run wizard
        run: |
          npx quorum-wizard -q
          cd network/3-nodes-quickstart
          ./start.sh
          cd -
      - name: Build and serve plugin from http://localhost:3000
        run: |
          yarn install
          yarn build
          yarn serve &
      - name: Run Chrome and Firefox tests on http://remix-dev.goquorum.com
        run: |
          yarn install
          yarn test_chrome_headless
          yarn test_firefox_headless
        env:
          RPC_SCHEME: http
          REMIX_URL: http://remix-dev.goquorum.com
          NODE_ONE_HOST: "localhost:22000"
          NODE_ONE_TESSERA: "localhost:9081"
          NODE_ONE_PUB_KEY: BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo=
          NODE_TWO_HOST: "localhost:22001"
          NODE_TWO_TESSERA: "localhost:9082"
          NODE_TWO_PUB_KEY: QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=
          NODE_THREE_HOST: "localhost:22002"
          NODE_THREE_TESSERA: "localhost:9083"
          NODE_THREE_PUB_KEY: 1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg=
      - name: Make reports/screenshots available
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports
