name: Build & Test

on:
  push:
    branches-ignore:
      - master
      - release/prod
      - gh-pages
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Build and serve plugin from http://localhost:3000
        run: |
          yarn install
          yarn build
          yarn serve &
      - name: Run Chrome and Firefox tests on http://remix-dev.goquorum.com
        run: |
          yarn install
          yarn test_chrome_headless
          yarn test_firefox_headless
        env:
          RPC_USERNAME: ${{ secrets.KaleidoUsername }}
          RPC_PASSWORD: ${{ secrets.KaleidoPassword }}
          RPC_SCHEME: http
          REMIX_URL: http://remix-dev.goquorum.com
          NODE_ONE_HOST: u0a5aft4j3-u0bu939ak6-rpc.us0-aws.kaleido.io
          NODE_ONE_TESSERA: u0a5aft4j3-u0bu939ak6-ptx.us0-aws.kaleido.io
          NODE_ONE_PUB_KEY: wj/d6GyPJpReu/xF+mecwR8qPAmZM73S+TzesU5y70Y=
          NODE_TWO_HOST: u0a5aft4j3-u0u5ulmm6k-rpc.us0-aws.kaleido.io
          NODE_TWO_TESSERA: u0a5aft4j3-u0u5ulmm6k-ptx.us0-aws.kaleido.io
          NODE_TWO_PUB_KEY: Cr4orZhLtEKXSu6XQVvfTDpTUTvXYVnPHuym+r92skk=
          NODE_THREE_HOST: u0a5aft4j3-u0sog5yz3u-rpc.us0-aws.kaleido.io
          NODE_THREE_TESSERA: u0a5aft4j3-u0sog5yz3u-ptx.us0-aws.kaleido.io
          NODE_THREE_PUB_KEY: MzL4UtMSfRm0dUG+X08cYj39/Sa5QFFBVWuc42YZkwg=
