name: Run Alpha Tests

on:
  schedule:
    - cron: "00 13 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run Chrome and Firefox tests on https://remix-alpha.ethereum.org
        run: |
          yarn install
          yarn test_chrome_headless
          yarn test_firefox_headless
        env:
          RPC_USERNAME: ${{ secrets.KaleidoUsername }}
          RPC_PASSWORD: ${{ secrets.KaleidoPassword }}
          RPC_SCHEME: https
          REMIX_URL: https://remix-alpha.ethereum.org
          NODE_ONE_HOST: u0suxofstd-u0ebuvkn9x-rpc.us0-aws.kaleido.io
          NODE_ONE_TESSERA: u0suxofstd-u0ebuvkn9x-ptx.us0-aws.kaleido.io
          NODE_ONE_PUB_KEY: +07DSpKfz/4OdhVeoGM+ggX2peoXvXjPf/p/iuzStkU=
          NODE_TWO_HOST: u0suxofstd-u0eidl9700-rpc.us0-aws.kaleido.io
          NODE_TWO_TESSERA: u0suxofstd-u0eidl9700-ptx.us0-aws.kaleido.io
          NODE_TWO_PUB_KEY: 2GotprZj8m1nSC1W0IC5xj2pDnTBdQG4k7GPbgVjJTQ=
          NODE_THREE_HOST: u0suxofstd-u0mi62ig6z-rpc.us0-aws.kaleido.io
          NODE_THREE_TESSERA: u0suxofstd-u0mi62ig6z-ptx.us0-aws.kaleido.io
          NODE_THREE_PUB_KEY: PEw8JvJPkBAuZ5UrQaHu6NuBHqIm+ICtRMhTzAnglBw=
      - name: Make reports/screenshots available
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports
